# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tw < Formula
  desc "'tw' is a very basic Twitter client to query your Likes, and do some powerful JSON filtering."
  homepage "https://github.com/embano1/tw"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/embano1/tw/releases/download/v1.2.0/tw_Darwin_x86_64.tar.gz"
      sha256 "169c8e69d9300e00fafb2d6a869dc369d02d9398d45198ad5ae75df0d46b063a"

      def install
        bin.install "tw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/embano1/tw/releases/download/v1.2.0/tw_Darwin_arm64.tar.gz"
      sha256 "aa9f225b3d351815dbb850f6888a9311f7d766f830b53acbed1b0fa4b619187a"

      def install
        bin.install "tw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/embano1/tw/releases/download/v1.2.0/tw_Linux_arm64.tar.gz"
      sha256 "b4748dc3beade5b092ad1031e91d2264ad000d00fdb784ce531492e562cb4c85"

      def install
        bin.install "tw"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/embano1/tw/releases/download/v1.2.0/tw_Linux_x86_64.tar.gz"
      sha256 "94d95a0bfd7bb3280f2f847d177c581b2dd0fd0263724bfc3d1e1f3029888984"

      def install
        bin.install "tw"
      end
    end
  end

  test do
    system "#{bin}/tw -v"
  end
end
